#!/usr/bin/env bash

set -e

REPOSITORY="git@github.com:Lyr-7D1h/home-manager.git"

if cat /proc/version | grep -i archlinux &>/dev/null; then

	echo "Installing packages for archlinux"
	sudo pacman -S nix git

	echo "Setting up nix"
	sudo systemctl --user enable --now nix-daemon
	sudo usermod -aG nix-users $USER
	nix-channel --add https://nixos.org/channels/nixpkgs-unstable
	nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager
	export NIX_PATH=$HOME/.nix-defexpr/channels:/nix/var/nix/profiles/per-user/root/channels${NIX_PATH:+:$NIX_PATH}
	nix-channel --update
	nix-shell '<home-manager>' -A install
	. "$HOME/.nix-profile/etc/profile.d/hm-session-vars.sh"
	
	echo "Setting up configuration"
	mkdir -f ~/.config
	rm -rf ~/.config/nixpkgs
	git clone $REPOSITORY ~/.config/nixpkgs 
	ln -s ~/.config/nixpkgs/bin ~/bin

	echo "Updating"
	home-manager switch

fi
